-- MySQL Script generated by MySQL Workbench
-- Mon Dec  7 19:55:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quickvey-19
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quickvey-19
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quickvey-19` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `quickvey-19` ;

-- -----------------------------------------------------
-- Table `quickvey-19`.`encuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quickvey-19`.`encuesta` (
  `id_encuesta` INT NOT NULL AUTO_INCREMENT,
  `id_registro` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `pregunta1` VARCHAR(45) NOT NULL,
  `pregunta2` VARCHAR(45) NOT NULL,
  `pregunta3` VARCHAR(45) NOT NULL,
  `pregunta4` VARCHAR(45) NOT NULL,
  `pregunta5` VARCHAR(45) NOT NULL,
  `pregunta6` VARCHAR(45) NOT NULL,
  `pregunta7` VARCHAR(45) NOT NULL,
  `pregunta8` VARCHAR(45) NOT NULL,
  `pregunta9` VARCHAR(45) NOT NULL,
  `pregunta10` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_encuesta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quickvey-19`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quickvey-19`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quickvey-19`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quickvey-19`.`registro` (
  `id_registro` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `encuesta_id_encuesta` INT NOT NULL,
  PRIMARY KEY (`id_registro`),
  INDEX `fk_registro_usuario_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_registro_encuesta1_idx` (`encuesta_id_encuesta` ASC) VISIBLE,
  CONSTRAINT `fk_registro_usuario`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `quickvey-19`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registro_encuesta1`
    FOREIGN KEY (`encuesta_id_encuesta`)
    REFERENCES `quickvey-19`.`encuesta` (`id_encuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quickvey-19`.`informacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quickvey-19`.`informacion` (
  `id_informacion` INT NOT NULL AUTO_INCREMENT,
  `id_registro` INT NOT NULL,
  `pregunta_info` VARCHAR(45) NOT NULL,
  `registro_id_registro` INT NOT NULL,
  PRIMARY KEY (`id_informacion`),
  INDEX `fk_informacion_registro1_idx` (`registro_id_registro` ASC) VISIBLE,
  CONSTRAINT `fk_informacion_registro1`
    FOREIGN KEY (`registro_id_registro`)
    REFERENCES `quickvey-19`.`registro` (`id_registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
