/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;

/**
 *
 * @author salvador.santos
 */
public class frmPantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPantallaPrincipal
     */
    public frmPantallaPrincipal() {
        initComponents();
        
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuSistema = new javax.swing.JMenu();
        opmResponderEncuesta = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        opmCerrarSesion = new javax.swing.JMenuItem();
        mnuCataogos = new javax.swing.JMenu();
        opmPreguntas = new javax.swing.JMenuItem();
        opmRespuestas = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        opmEncuestas = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        opmPersonas = new javax.swing.JMenuItem();
        mnuSeguridad = new javax.swing.JMenu();
        opmUsuarios = new javax.swing.JMenuItem();
        opmPerfiles = new javax.swing.JMenuItem();
        opmEditarPerfil = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        opmCambiarPassword = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setMinimumSize(new java.awt.Dimension(294, 30));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(294, 30));

        mnuSistema.setText("Sistema");
        mnuSistema.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        mnuSistema.setPreferredSize(new java.awt.Dimension(75, 25));

        opmResponderEncuesta.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        opmResponderEncuesta.setText("Encuestas");
        mnuSistema.add(opmResponderEncuesta);
        mnuSistema.add(jSeparator1);

        opmCerrarSesion.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        opmCerrarSesion.setText("Cerrar Sesión");
        mnuSistema.add(opmCerrarSesion);

        jMenuBar1.add(mnuSistema);

        mnuCataogos.setText("Catálogos");
        mnuCataogos.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        mnuCataogos.setPreferredSize(new java.awt.Dimension(85, 25));

        opmPreguntas.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        opmPreguntas.setText("Preguntas");
        mnuCataogos.add(opmPreguntas);

        opmRespuestas.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        opmRespuestas.setText("Respuestas");
        mnuCataogos.add(opmRespuestas);
        mnuCataogos.add(jSeparator2);

        opmEncuestas.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        opmEncuestas.setText("Encuestas");
        opmEncuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opmEncuestasActionPerformed(evt);
            }
        });
        mnuCataogos.add(opmEncuestas);
        mnuCataogos.add(jSeparator3);

        opmPersonas.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        opmPersonas.setText("Personas");
        mnuCataogos.add(opmPersonas);

        jMenuBar1.add(mnuCataogos);

        mnuSeguridad.setText("Seguridad");
        mnuSeguridad.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        mnuSeguridad.setPreferredSize(new java.awt.Dimension(85, 25));

        opmUsuarios.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        opmUsuarios.setText("Usuarios");
        mnuSeguridad.add(opmUsuarios);

        opmPerfiles.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        opmPerfiles.setText("Perfiles");
        opmPerfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opmPerfilesActionPerformed(evt);
            }
        });
        mnuSeguridad.add(opmPerfiles);

        jMenuBar1.add(mnuSeguridad);

        opmEditarPerfil.setText("Opciones");
        opmEditarPerfil.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        opmEditarPerfil.setPreferredSize(new java.awt.Dimension(80, 25));

        jMenuItem9.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jMenuItem9.setText("Perfil");
        opmEditarPerfil.add(jMenuItem9);
        opmEditarPerfil.add(jSeparator4);

        opmCambiarPassword.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        opmCambiarPassword.setText("Cambiar Contraseña");
        opmEditarPerfil.add(opmCambiarPassword);

        jMenuBar1.add(opmEditarPerfil);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opmPerfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opmPerfilesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opmPerfilesActionPerformed

    private void opmEncuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opmEncuestasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opmEncuestasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    public javax.swing.JMenu mnuCataogos;
    public javax.swing.JMenu mnuSeguridad;
    public javax.swing.JMenu mnuSistema;
    public javax.swing.JMenuItem opmCambiarPassword;
    public javax.swing.JMenuItem opmCerrarSesion;
    public javax.swing.JMenu opmEditarPerfil;
    public javax.swing.JMenuItem opmEncuestas;
    public javax.swing.JMenuItem opmPerfiles;
    public javax.swing.JMenuItem opmPersonas;
    public javax.swing.JMenuItem opmPreguntas;
    public javax.swing.JMenuItem opmResponderEncuesta;
    public javax.swing.JMenuItem opmRespuestas;
    public javax.swing.JMenuItem opmUsuarios;
    // End of variables declaration//GEN-END:variables
}
